"""control plane initial

Revision ID: 8012b5305064
Revises:
Create Date: 2026-09-09 09:51:56.278412
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "8012b5305064"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("included_modules", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("price_per_student_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("max_students", sa.Integer(), nullable=True),
        sa.Column("max_staff", sa.Integer(), nullable=True),
        sa.Column("max_api_requests_per_day", sa.Integer(), nullable=True),
        sa.Column("support_tier", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan")),
        sa.UniqueConstraint("code", name=op.f("uq_plan_code")),
    )
    op.create_index(op.f("ix_plan_created_at"), "plan", ["created_at"], unique=False)
    op.create_table(
        "platform_audit_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=True),
        sa.Column("resource_id", sa.String(length=80), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_audit_event")),
    )
    op.create_index(
        op.f("ix_platform_audit_event_action"), "platform_audit_event", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_platform_audit_event_actor_id"), "platform_audit_event", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_platform_audit_event_occurred_at"),
        "platform_audit_event",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_audit_event_request_id"),
        "platform_audit_event",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_audit_event_tenant_id"),
        "platform_audit_event",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_tenant_time",
        "platform_audit_event",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "platform_user",
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("permissions", postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("mfa_secret", sa.String(length=120), nullable=True),
        sa.Column("mfa_enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_user")),
    )
    op.create_index(
        op.f("ix_platform_user_created_at"), "platform_user", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_platform_user_email"), "platform_user", ["email"], unique=True)
    op.create_table(
        "tenant",
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_name", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("database_name", sa.String(length=63), nullable=False),
        sa.Column("database_dsn", sa.Text(), nullable=True),
        sa.Column("region", sa.String(length=20), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("timezone", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("regulator_code", sa.String(length=20), nullable=True),
        sa.Column("accreditation_number", sa.String(length=60), nullable=True),
        sa.Column("website", sa.String(length=200), nullable=True),
        sa.Column("support_email", sa.String(length=200), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("crest_url", sa.String(length=500), nullable=True),
        sa.Column("brand_primary", sa.String(length=40), nullable=True),
        sa.Column("brand_accent", sa.String(length=40), nullable=True),
        sa.Column("enabled_features", postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("runtime_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_revision", sa.Integer(), nullable=False),
        sa.Column("schema_revision", sa.String(length=40), nullable=True),
        sa.Column("schema_migrated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("onboarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspension_reason", sa.String(length=500), nullable=True),
        sa.Column("purge_after", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("database_name", name=op.f("uq_tenant_database_name")),
    )
    op.create_index(op.f("ix_tenant_created_at"), "tenant", ["created_at"], unique=False)
    op.create_index(
        "ix_tenant_purge",
        "tenant",
        ["purge_after"],
        unique=False,
        postgresql_where=sa.text("purge_after IS NOT NULL"),
    )
    op.create_index(op.f("ix_tenant_slug"), "tenant", ["slug"], unique=True)
    op.create_index(op.f("ix_tenant_status"), "tenant", ["status"], unique=False)
    op.create_index("ix_tenant_status_region", "tenant", ["status", "region"], unique=False)
    op.create_table(
        "impersonation_session",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("platform_user_id", sa.UUID(), nullable=False),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("ticket_reference", sa.String(length=80), nullable=True),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actions_taken", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_user.id"],
            name=op.f("fk_impersonation_session_platform_user_id_platform_user"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_impersonation_session_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_impersonation_session")),
    )
    op.create_index(
        op.f("ix_impersonation_session_created_at"),
        "impersonation_session",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_impersonation_session_platform_user_id"),
        "impersonation_session",
        ["platform_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_impersonation_session_tenant_id"),
        "impersonation_session",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "subscription",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("renews_on", sa.Date(), nullable=True),
        sa.Column("trial_ends_on", sa.Date(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_days", sa.Integer(), nullable=False),
        sa.Column("billed_student_count", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plan.id"], name=op.f("fk_subscription_plan_id_plan")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_subscription_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
        sa.UniqueConstraint("tenant_id", name=op.f("uq_subscription_tenant_id")),
    )
    op.create_index(
        op.f("ix_subscription_created_at"), "subscription", ["created_at"], unique=False
    )
    op.create_table(
        "tenant_domain",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_token", sa.String(length=80), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_tenant_domain_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_domain")),
    )
    op.create_index(
        op.f("ix_tenant_domain_created_at"), "tenant_domain", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_tenant_domain_hostname"), "tenant_domain", ["hostname"], unique=True)
    op.create_index(
        op.f("ix_tenant_domain_tenant_id"), "tenant_domain", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_tenant_domain_primary",
        "tenant_domain",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("is_primary IS true"),
    )
    op.create_table(
        "tenant_migration",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("from_revision", sa.String(length=40), nullable=True),
        sa.Column("to_revision", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("triggered_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_tenant_migration_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_migration")),
        sa.UniqueConstraint(
            "tenant_id", "to_revision", "started_at", name="uq_tenant_migration_run"
        ),
    )
    op.create_index(
        op.f("ix_tenant_migration_created_at"), "tenant_migration", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_migration_tenant_id"), "tenant_migration", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenant_migration_tenant_id"), table_name="tenant_migration")
    op.drop_index(op.f("ix_tenant_migration_created_at"), table_name="tenant_migration")
    op.drop_table("tenant_migration")
    op.drop_index(
        "uq_tenant_domain_primary",
        table_name="tenant_domain",
        postgresql_where=sa.text("is_primary IS true"),
    )
    op.drop_index(op.f("ix_tenant_domain_tenant_id"), table_name="tenant_domain")
    op.drop_index(op.f("ix_tenant_domain_hostname"), table_name="tenant_domain")
    op.drop_index(op.f("ix_tenant_domain_created_at"), table_name="tenant_domain")
    op.drop_table("tenant_domain")
    op.drop_index(op.f("ix_subscription_created_at"), table_name="subscription")
    op.drop_table("subscription")
    op.drop_index(op.f("ix_impersonation_session_tenant_id"), table_name="impersonation_session")
    op.drop_index(
        op.f("ix_impersonation_session_platform_user_id"), table_name="impersonation_session"
    )
    op.drop_index(op.f("ix_impersonation_session_created_at"), table_name="impersonation_session")
    op.drop_table("impersonation_session")
    op.drop_index("ix_tenant_status_region", table_name="tenant")
    op.drop_index(op.f("ix_tenant_status"), table_name="tenant")
    op.drop_index(op.f("ix_tenant_slug"), table_name="tenant")
    op.drop_index(
        "ix_tenant_purge", table_name="tenant", postgresql_where=sa.text("purge_after IS NOT NULL")
    )
    op.drop_index(op.f("ix_tenant_created_at"), table_name="tenant")
    op.drop_table("tenant")
    op.drop_index(op.f("ix_platform_user_email"), table_name="platform_user")
    op.drop_index(op.f("ix_platform_user_created_at"), table_name="platform_user")
    op.drop_table("platform_user")
    op.drop_index("ix_platform_audit_tenant_time", table_name="platform_audit_event")
    op.drop_index(op.f("ix_platform_audit_event_tenant_id"), table_name="platform_audit_event")
    op.drop_index(op.f("ix_platform_audit_event_request_id"), table_name="platform_audit_event")
    op.drop_index(op.f("ix_platform_audit_event_occurred_at"), table_name="platform_audit_event")
    op.drop_index(op.f("ix_platform_audit_event_actor_id"), table_name="platform_audit_event")
    op.drop_index(op.f("ix_platform_audit_event_action"), table_name="platform_audit_event")
    op.drop_table("platform_audit_event")
    op.drop_index(op.f("ix_plan_created_at"), table_name="plan")
    op.drop_table("plan")
    # ### end Alembic commands ###
