"""learning and interop

Revision ID: e88eecdb22aa
Revises: 63b53e7141fc
Create Date: 2026-09-09 10:18:49.434134
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "e88eecdb22aa"
down_revision: str | None = "63b53e7141fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engagement_snapshot",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("course_offering_id", sa.UUID(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("captured_on", sa.Date(), nullable=False),
        sa.Column("materials_available", sa.Integer(), nullable=False),
        sa.Column("materials_viewed", sa.Integer(), nullable=False),
        sa.Column("minutes_on_material", sa.Integer(), nullable=False),
        sa.Column("assessments_available", sa.Integer(), nullable=False),
        sa.Column("assessments_attempted", sa.Integer(), nullable=False),
        sa.Column("mean_assessment_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("assignments_due", sa.Integer(), nullable=False),
        sa.Column("assignments_submitted", sa.Integer(), nullable=False),
        sa.Column("days_since_last_activity", sa.Integer(), nullable=True),
        sa.Column("risk_band", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engagement_snapshot")),
        sa.UniqueConstraint(
            "student_id", "course_offering_id", "week_number", name="uq_engagement_week"
        ),
    )
    op.create_index(
        "ix_engagement_risk",
        "engagement_snapshot",
        ["course_offering_id", "risk_band", "captured_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_engagement_snapshot_captured_on"),
        "engagement_snapshot",
        ["captured_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_engagement_snapshot_course_offering_id"),
        "engagement_snapshot",
        ["course_offering_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_engagement_snapshot_risk_band"), "engagement_snapshot", ["risk_band"], unique=False
    )
    op.create_index(
        op.f("ix_engagement_snapshot_student_id"),
        "engagement_snapshot",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "external_identifier",
        sa.Column("system", sa.String(length=40), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("external_type", sa.String(length=60), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_identifier")),
        sa.UniqueConstraint("system", "external_id", name="uq_external_identifier_theirs"),
        sa.UniqueConstraint(
            "system", "resource_type", "resource_id", name="uq_external_identifier_ours"
        ),
    )
    op.create_index(
        op.f("ix_external_identifier_created_at"),
        "external_identifier",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_identifier_created_by_id"),
        "external_identifier",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_identifier_deleted_at"),
        "external_identifier",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_identifier_external_id"),
        "external_identifier",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_identifier_resource_id"),
        "external_identifier",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_identifier_resource_type"),
        "external_identifier",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_identifier_system"), "external_identifier", ["system"], unique=False
    )
    op.create_table(
        "lti_nonce",
        sa.Column("nonce", sa.String(length=120), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_id", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("nonce", name=op.f("pk_lti_nonce")),
    )
    op.create_index(op.f("ix_lti_nonce_issued_at"), "lti_nonce", ["issued_at"], unique=False)
    op.create_table(
        "lti_platform_key",
        sa.Column("kid", sa.String(length=64), nullable=False),
        sa.Column("algorithm", sa.String(length=10), nullable=False),
        sa.Column("public_key_pem", sa.Text(), nullable=False),
        sa.Column("private_key_ref", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lti_platform_key")),
    )
    op.create_index(
        op.f("ix_lti_platform_key_created_at"), "lti_platform_key", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_lti_platform_key_created_by_id"),
        "lti_platform_key",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lti_platform_key_deleted_at"), "lti_platform_key", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_lti_platform_key_is_active"), "lti_platform_key", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_lti_platform_key_kid"), "lti_platform_key", ["kid"], unique=True)
    op.create_table(
        "lti_tool",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=120), nullable=False),
        sa.Column("issuer", sa.String(length=300), nullable=False),
        sa.Column("oidc_login_url", sa.String(length=500), nullable=False),
        sa.Column("target_link_uri", sa.String(length=500), nullable=False),
        sa.Column("jwks_url", sa.String(length=500), nullable=True),
        sa.Column("public_key_pem", sa.Text(), nullable=True),
        sa.Column("deployment_id", sa.String(length=80), nullable=False),
        sa.Column("allow_deep_linking", sa.Boolean(), nullable=False),
        sa.Column("allow_grade_services", sa.Boolean(), nullable=False),
        sa.Column("allow_names_and_roles", sa.Boolean(), nullable=False),
        sa.Column("disclose_emails", sa.Boolean(), nullable=False),
        sa.Column("custom_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_launch_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("launch_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lti_tool")),
        sa.UniqueConstraint("client_id", "deployment_id", name="uq_lti_deployment"),
    )
    op.create_index(op.f("ix_lti_tool_client_id"), "lti_tool", ["client_id"], unique=True)
    op.create_index(op.f("ix_lti_tool_created_at"), "lti_tool", ["created_at"], unique=False)
    op.create_index(op.f("ix_lti_tool_created_by_id"), "lti_tool", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_lti_tool_deleted_at"), "lti_tool", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_lti_tool_status"), "lti_tool", ["status"], unique=False)
    op.create_table(
        "xapi_statement",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_student_id", sa.UUID(), nullable=True),
        sa.Column("verb", sa.String(length=300), nullable=False),
        sa.Column("object_iri", sa.String(length=500), nullable=False),
        sa.Column("course_offering_id", sa.UUID(), nullable=True),
        sa.Column("tool_id", sa.UUID(), nullable=True),
        sa.Column("result_score_scaled", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("result_success", sa.Boolean(), nullable=True),
        sa.Column("result_completion", sa.Boolean(), nullable=True),
        sa.Column("statement", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xapi_statement")),
    )
    op.create_index(
        op.f("ix_xapi_statement_actor_student_id"),
        "xapi_statement",
        ["actor_student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_xapi_statement_course_offering_id"),
        "xapi_statement",
        ["course_offering_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_xapi_statement_object_iri"), "xapi_statement", ["object_iri"], unique=False
    )
    op.create_index(
        op.f("ix_xapi_statement_stored_at"), "xapi_statement", ["stored_at"], unique=False
    )
    op.create_index(op.f("ix_xapi_statement_verb"), "xapi_statement", ["verb"], unique=False)
    op.create_index(
        "ix_xapi_student_time", "xapi_statement", ["actor_student_id", "occurred_at"], unique=False
    )
    op.create_table(
        "question_bank",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("course_id", sa.UUID(), nullable=True),
        sa.Column("owning_unit_id", sa.UUID(), nullable=True),
        sa.Column("department_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("faculty_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_question_bank_course_id_course"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owning_unit_id"],
            ["academic_unit.id"],
            name=op.f("fk_question_bank_owning_unit_id_academic_unit"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_bank")),
        sa.UniqueConstraint("code", name="uq_question_bank_code"),
    )
    op.create_index(op.f("ix_question_bank_code"), "question_bank", ["code"], unique=False)
    op.create_index(
        op.f("ix_question_bank_course_id"), "question_bank", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_bank_created_at"), "question_bank", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_question_bank_created_by_id"), "question_bank", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_bank_deleted_at"), "question_bank", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_question_bank_owning_unit_id"), "question_bank", ["owning_unit_id"], unique=False
    )
    op.create_table(
        "question",
        sa.Column("bank_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("stem", sa.Text(), nullable=False),
        sa.Column("attachment_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("marks", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("negative_marks", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("answer_key", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("variable_sets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("learning_outcome", sa.String(length=300), nullable=True),
        sa.Column("topic", sa.String(length=200), nullable=True),
        sa.Column("cognitive_level", sa.String(length=20), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("times_used", sa.Integer(), nullable=False),
        sa.Column("times_answered", sa.Integer(), nullable=False),
        sa.Column("facility_index", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("discrimination_index", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint("marks > 0", name=op.f("ck_question_question_marks_positive")),
        sa.ForeignKeyConstraint(
            ["bank_id"],
            ["question_bank.id"],
            name=op.f("fk_question_bank_id_question_bank"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question")),
    )
    op.create_index(op.f("ix_question_bank_id"), "question", ["bank_id"], unique=False)
    op.create_index(
        "ix_question_bank_kind", "question", ["bank_id", "kind", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_question_cognitive_level"), "question", ["cognitive_level"], unique=False
    )
    op.create_index(op.f("ix_question_created_at"), "question", ["created_at"], unique=False)
    op.create_index(op.f("ix_question_created_by_id"), "question", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_question_deleted_at"), "question", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_question_is_active"), "question", ["is_active"], unique=False)
    op.create_index(op.f("ix_question_kind"), "question", ["kind"], unique=False)
    op.create_index(op.f("ix_question_topic"), "question", ["topic"], unique=False)
    op.create_table(
        "question_option",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=10), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("pin_position", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk_question_option_question_id_question"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_option")),
        sa.UniqueConstraint("question_id", "label", name="uq_question_option_label"),
    )
    op.create_index(
        op.f("ix_question_option_created_at"), "question_option", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_question_option_created_by_id"), "question_option", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_option_deleted_at"), "question_option", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_question_option_question_id"), "question_option", ["question_id"], unique=False
    )
    op.create_table(
        "course_space",
        sa.Column("course_offering_id", sa.UUID(), nullable=False),
        sa.Column("semester_id", sa.UUID(), nullable=False),
        sa.Column("department_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("faculty_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("welcome_message", sa.Text(), nullable=True),
        sa.Column("syllabus_outline", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_offering_id"],
            ["course_offering.id"],
            name=op.f("fk_course_space_course_offering_id_course_offering"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semester.id"],
            name=op.f("fk_course_space_semester_id_semester"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_space")),
    )
    op.create_index(
        op.f("ix_course_space_course_offering_id"),
        "course_space",
        ["course_offering_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_course_space_created_at"), "course_space", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_course_space_created_by_id"), "course_space", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_space_deleted_at"), "course_space", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_course_space_is_published"), "course_space", ["is_published"], unique=False
    )
    op.create_index(
        op.f("ix_course_space_semester_id"), "course_space", ["semester_id"], unique=False
    )
    op.create_table(
        "assignment",
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("course_offering_id", sa.UUID(), nullable=False),
        sa.Column("assessment_component_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column("attachment_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("total_marks", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accept_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("late_penalty_percent_per_day", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("submission_mode", sa.String(length=20), nullable=False),
        sa.Column("max_file_count", sa.Integer(), nullable=False),
        sa.Column("allowed_extensions", postgresql.ARRAY(sa.String(length=10)), nullable=False),
        sa.Column("max_file_bytes", sa.Integer(), nullable=False),
        sa.Column("similarity_check", sa.Boolean(), nullable=False),
        sa.Column("similarity_threshold_percent", sa.Integer(), nullable=True),
        sa.Column("blind_marking", sa.Boolean(), nullable=False),
        sa.Column("double_marking", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pushed_to_mark_sheet_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("department_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("faculty_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_component_id"],
            ["assessment_component.id"],
            name=op.f("fk_assignment_assessment_component_id_assessment_component"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["course_offering_id"],
            ["course_offering.id"],
            name=op.f("fk_assignment_course_offering_id_course_offering"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["course_space.id"],
            name=op.f("fk_assignment_space_id_course_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignment")),
    )
    op.create_index(
        op.f("ix_assignment_course_offering_id"), "assignment", ["course_offering_id"], unique=False
    )
    op.create_index(op.f("ix_assignment_created_at"), "assignment", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_assignment_created_by_id"), "assignment", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_assignment_deleted_at"), "assignment", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_assignment_due_at"), "assignment", ["due_at"], unique=False)
    op.create_index(op.f("ix_assignment_space_id"), "assignment", ["space_id"], unique=False)
    op.create_index(op.f("ix_assignment_status"), "assignment", ["status"], unique=False)
    op.create_table(
        "content_package",
        sa.Column("format", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_system", sa.String(length=80), nullable=True),
        sa.Column("attachment_id", sa.UUID(), nullable=True),
        sa.Column("space_id", sa.UUID(), nullable=True),
        sa.Column("question_bank_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("items_found", sa.Integer(), nullable=False),
        sa.Column("items_imported", sa.Integer(), nullable=False),
        sa.Column("failures", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("imported_by_id", sa.UUID(), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_bank_id"],
            ["question_bank.id"],
            name=op.f("fk_content_package_question_bank_id_question_bank"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["course_space.id"],
            name=op.f("fk_content_package_space_id_course_space"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_package")),
    )
    op.create_index(
        op.f("ix_content_package_created_at"), "content_package", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_content_package_created_by_id"), "content_package", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_content_package_deleted_at"), "content_package", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_content_package_format"), "content_package", ["format"], unique=False)
    op.create_index(
        op.f("ix_content_package_question_bank_id"),
        "content_package",
        ["question_bank_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_package_space_id"), "content_package", ["space_id"], unique=False
    )
    op.create_index(op.f("ix_content_package_status"), "content_package", ["status"], unique=False)
    op.create_table(
        "lti_resource_link",
        sa.Column("tool_id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=True),
        sa.Column("course_offering_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("custom", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("presentation", sa.String(length=20), nullable=False),
        sa.Column("assessment_component_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_component_id"],
            ["assessment_component.id"],
            name=op.f("fk_lti_resource_link_assessment_component_id_assessment_component"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["course_offering_id"],
            ["course_offering.id"],
            name=op.f("fk_lti_resource_link_course_offering_id_course_offering"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["course_space.id"],
            name=op.f("fk_lti_resource_link_space_id_course_space"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["lti_tool.id"],
            name=op.f("fk_lti_resource_link_tool_id_lti_tool"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lti_resource_link")),
    )
    op.create_index(
        op.f("ix_lti_resource_link_course_offering_id"),
        "lti_resource_link",
        ["course_offering_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lti_resource_link_created_at"), "lti_resource_link", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_lti_resource_link_created_by_id"),
        "lti_resource_link",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lti_resource_link_deleted_at"), "lti_resource_link", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_lti_resource_link_space_id"), "lti_resource_link", ["space_id"], unique=False
    )
    op.create_index(
        op.f("ix_lti_resource_link_tool_id"), "lti_resource_link", ["tool_id"], unique=False
    )
    op.create_table(
        "material",
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("week_number", sa.Integer(), nullable=True),
        sa.Column("topic", sa.String(length=200), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.UUID(), nullable=True),
        sa.Column("external_url", sa.String(length=1000), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requires_fee_clearance", sa.Boolean(), nullable=False),
        sa.Column("allow_download", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("unique_viewer_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["course_space.id"],
            name=op.f("fk_material_space_id_course_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material")),
    )
    op.create_index(op.f("ix_material_created_at"), "material", ["created_at"], unique=False)
    op.create_index(op.f("ix_material_created_by_id"), "material", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_material_deleted_at"), "material", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_material_is_published"), "material", ["is_published"], unique=False)
    op.create_index(op.f("ix_material_kind"), "material", ["kind"], unique=False)
    op.create_index(op.f("ix_material_space_id"), "material", ["space_id"], unique=False)
    op.create_index(
        "ix_material_space_week", "material", ["space_id", "week_number", "sequence"], unique=False
    )
    op.create_index(op.f("ix_material_week_number"), "material", ["week_number"], unique=False)
    op.create_table(
        "online_assessment",
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("course_offering_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("assessment_component_id", sa.UUID(), nullable=True),
        sa.Column("total_marks", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("pass_mark_percent", sa.Integer(), nullable=True),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("attempt_grading", sa.String(length=20), nullable=False),
        sa.Column("behaviour", sa.String(length=30), nullable=False),
        sa.Column("tries_per_question", sa.Integer(), nullable=False),
        sa.Column("try_penalty_fraction", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("shuffle_questions", sa.Boolean(), nullable=False),
        sa.Column("shuffle_options", sa.Boolean(), nullable=False),
        sa.Column("one_question_per_page", sa.Boolean(), nullable=False),
        sa.Column("allow_backtracking", sa.Boolean(), nullable=False),
        sa.Column("access_password_hash", sa.String(length=64), nullable=True),
        sa.Column("allowed_ip_ranges", postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("monitor_focus_loss", sa.Boolean(), nullable=False),
        sa.Column("max_focus_losses", sa.Integer(), nullable=True),
        sa.Column("require_webcam", sa.Boolean(), nullable=False),
        sa.Column("score_visibility", sa.String(length=20), nullable=False),
        sa.Column("show_correct_answers", sa.Boolean(), nullable=False),
        sa.Column("show_explanations", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("authored_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comments", sa.Text(), nullable=True),
        sa.Column("released_by_id", sa.UUID(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pushed_to_mark_sheet_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("submitted_count", sa.Integer(), nullable=False),
        sa.Column("mean_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("median_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("standard_deviation", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("pending_manual_marking", sa.Integer(), nullable=False),
        sa.Column("department_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("faculty_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_online_assessment_attempts_at_least_one")
        ),
        sa.ForeignKeyConstraint(
            ["assessment_component_id"],
            ["assessment_component.id"],
            name=op.f("fk_online_assessment_assessment_component_id_assessment_component"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["course_offering_id"],
            ["course_offering.id"],
            name=op.f("fk_online_assessment_course_offering_id_course_offering"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["course_space.id"],
            name=op.f("fk_online_assessment_space_id_course_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_online_assessment")),
    )
    op.create_index(
        op.f("ix_online_assessment_assessment_component_id"),
        "online_assessment",
        ["assessment_component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_assessment_closes_at"), "online_assessment", ["closes_at"], unique=False
    )
    op.create_index(
        op.f("ix_online_assessment_course_offering_id"),
        "online_assessment",
        ["course_offering_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_assessment_created_at"), "online_assessment", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_online_assessment_created_by_id"),
        "online_assessment",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_assessment_deleted_at"), "online_assessment", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_online_assessment_kind"), "online_assessment", ["kind"], unique=False)
    op.create_index(
        op.f("ix_online_assessment_opens_at"), "online_assessment", ["opens_at"], unique=False
    )
    op.create_index(
        op.f("ix_online_assessment_space_id"), "online_assessment", ["space_id"], unique=False
    )
    op.create_index(
        op.f("ix_online_assessment_status"), "online_assessment", ["status"], unique=False
    )
    op.create_index(
        "ix_online_assessment_window",
        "online_assessment",
        ["status", "opens_at", "closes_at"],
        unique=False,
    )
    op.create_table(
        "assessment_attempt",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_time_minutes", sa.Integer(), nullable=False),
        sa.Column("extra_time_reason", sa.String(length=300), nullable=True),
        sa.Column("presented_paper", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("auto_score", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("manual_score", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("total_score", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("marked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("marked_by_id", sa.UUID(), nullable=True),
        sa.Column("counts_for_grade", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(length=60), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("integrity_events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("focus_loss_count", sa.Integer(), nullable=False),
        sa.Column("resumption_count", sa.Integer(), nullable=False),
        sa.Column("integrity_review", sa.Text(), nullable=True),
        sa.Column("integrity_reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("voided_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["online_assessment.id"],
            name=op.f("fk_assessment_attempt_assessment_id_online_assessment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk_assessment_attempt_student_id_student"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_attempt")),
        sa.UniqueConstraint(
            "assessment_id", "student_id", "attempt_number", name="uq_attempt_number"
        ),
    )
    op.create_index(
        op.f("ix_assessment_attempt_assessment_id"),
        "assessment_attempt",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_attempt_created_at"), "assessment_attempt", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_attempt_created_by_id"),
        "assessment_attempt",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_attempt_deleted_at"), "assessment_attempt", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_attempt_expires_at"), "assessment_attempt", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_attempt_status"), "assessment_attempt", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_attempt_student_id"), "assessment_attempt", ["student_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_attempt_total_score"),
        "assessment_attempt",
        ["total_score"],
        unique=False,
    )
    op.create_index("ix_attempt_live", "assessment_attempt", ["status", "expires_at"], unique=False)
    op.create_table(
        "assessment_item",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=80), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=True),
        sa.Column("bank_id", sa.UUID(), nullable=True),
        sa.Column("draw_count", sa.Integer(), nullable=False),
        sa.Column("draw_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("marks_override", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "(mode = 'fixed' AND question_id IS NOT NULL) OR (mode = 'pooled' AND bank_id IS NOT NULL)",
            name=op.f("ck_assessment_item_item_has_a_source"),
        ),
        sa.CheckConstraint("draw_count >= 1", name=op.f("ck_assessment_item_draw_at_least_one")),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["online_assessment.id"],
            name=op.f("fk_assessment_item_assessment_id_online_assessment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"],
            ["question_bank.id"],
            name=op.f("fk_assessment_item_bank_id_question_bank"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk_assessment_item_question_id_question"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_item")),
    )
    op.create_index(
        op.f("ix_assessment_item_assessment_id"), "assessment_item", ["assessment_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_item_created_at"), "assessment_item", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_item_created_by_id"), "assessment_item", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_item_deleted_at"), "assessment_item", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_item_question_id"), "assessment_item", ["question_id"], unique=False
    )
    op.create_table(
        "assignment_submission",
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("group_member_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attachment_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("text_response", sa.Text(), nullable=True),
        sa.Column("days_late", sa.Integer(), nullable=False),
        sa.Column("penalty_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("raw_score", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("final_score", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rubric_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("feedback_attachment_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("marked_by_id", sa.UUID(), nullable=True),
        sa.Column("marked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("second_marked_by_id", sa.UUID(), nullable=True),
        sa.Column("second_score", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("reconciled_score", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("reconciled_by_id", sa.UUID(), nullable=True),
        sa.Column("similarity_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("similarity_report_id", sa.UUID(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignment.id"],
            name=op.f("fk_assignment_submission_assignment_id_assignment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk_assignment_submission_student_id_student"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignment_submission")),
        sa.UniqueConstraint(
            "assignment_id", "student_id", "attempt_number", name="uq_submission_attempt"
        ),
    )
    op.create_index(
        op.f("ix_assignment_submission_assignment_id"),
        "assignment_submission",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_submission_created_at"),
        "assignment_submission",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_submission_created_by_id"),
        "assignment_submission",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_submission_deleted_at"),
        "assignment_submission",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_submission_status"), "assignment_submission", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_assignment_submission_student_id"),
        "assignment_submission",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        "ix_submission_marking_queue",
        "assignment_submission",
        ["assignment_id", "status"],
        unique=False,
    )
    op.create_table(
        "lti_line_item",
        sa.Column("resource_link_id", sa.UUID(), nullable=True),
        sa.Column("tool_id", sa.UUID(), nullable=False),
        sa.Column("course_offering_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("score_maximum", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("resource_id", sa.String(length=200), nullable=True),
        sa.Column("tag", sa.String(length=120), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assessment_component_id", sa.UUID(), nullable=True),
        sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "score_maximum > 0", name=op.f("ck_lti_line_item_line_item_maximum_positive")
        ),
        sa.ForeignKeyConstraint(
            ["assessment_component_id"],
            ["assessment_component.id"],
            name=op.f("fk_lti_line_item_assessment_component_id_assessment_component"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["course_offering_id"],
            ["course_offering.id"],
            name=op.f("fk_lti_line_item_course_offering_id_course_offering"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_link_id"],
            ["lti_resource_link.id"],
            name=op.f("fk_lti_line_item_resource_link_id_lti_resource_link"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["lti_tool.id"],
            name=op.f("fk_lti_line_item_tool_id_lti_tool"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lti_line_item")),
    )
    op.create_index(
        op.f("ix_lti_line_item_course_offering_id"),
        "lti_line_item",
        ["course_offering_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lti_line_item_created_at"), "lti_line_item", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_lti_line_item_created_by_id"), "lti_line_item", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_lti_line_item_deleted_at"), "lti_line_item", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_lti_line_item_resource_id"), "lti_line_item", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_lti_line_item_resource_link_id"),
        "lti_line_item",
        ["resource_link_id"],
        unique=False,
    )
    op.create_index(op.f("ix_lti_line_item_tool_id"), "lti_line_item", ["tool_id"], unique=False)
    op.create_table(
        "material_view",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("first_viewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_viewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("total_seconds", sa.Integer(), nullable=False),
        sa.Column("downloaded", sa.Boolean(), nullable=False),
        sa.Column("completion_percent", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["material.id"],
            name=op.f("fk_material_view_material_id_material"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_view")),
        sa.UniqueConstraint("material_id", "student_id", name="uq_material_view"),
    )
    op.create_index(
        op.f("ix_material_view_material_id"), "material_view", ["material_id"], unique=False
    )
    op.create_index(
        "ix_material_view_student", "material_view", ["student_id", "last_viewed_at"], unique=False
    )
    op.create_index(
        op.f("ix_material_view_student_id"), "material_view", ["student_id"], unique=False
    )
    op.create_table(
        "assessment_response",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=True),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("question_revision", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seconds_spent", sa.Integer(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("marks_available", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("fraction", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("marks_awarded", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("tries_used", sa.Integer(), nullable=False),
        sa.Column("penalty_fraction", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("try_history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("marked_by", sa.String(length=10), nullable=True),
        sa.Column("marked_by_id", sa.UUID(), nullable=True),
        sa.Column("marker_comment", sa.Text(), nullable=True),
        sa.Column("rubric_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("queried_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("query_note", sa.Text(), nullable=True),
        sa.Column("query_resolution", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.Column("deletion_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempt.id"],
            name=op.f("fk_assessment_response_attempt_id_assessment_attempt"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["assessment_item.id"],
            name=op.f("fk_assessment_response_item_id_assessment_item"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name=op.f("fk_assessment_response_question_id_question"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_response")),
        sa.UniqueConstraint("attempt_id", "question_id", name="uq_response_question"),
    )
    op.create_index(
        op.f("ix_assessment_response_attempt_id"),
        "assessment_response",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_response_created_at"),
        "assessment_response",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_response_created_by_id"),
        "assessment_response",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_response_deleted_at"),
        "assessment_response",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_response_question_id"),
        "assessment_response",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        "ix_response_marking_queue",
        "assessment_response",
        ["question_id", "marks_awarded"],
        unique=False,
    )
    op.create_table(
        "lti_score",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("line_item_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score_given", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("score_maximum", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("activity_progress", sa.String(length=20), nullable=False),
        sa.Column("grading_progress", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_item_id"],
            ["lti_line_item.id"],
            name=op.f("fk_lti_score_line_item_id_lti_line_item"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lti_score")),
    )
    op.create_index(
        "ix_lti_score_current",
        "lti_score",
        ["line_item_id", "student_id", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_lti_score_line_item_id"), "lti_score", ["line_item_id"], unique=False)
    op.create_index(op.f("ix_lti_score_received_at"), "lti_score", ["received_at"], unique=False)
    op.create_index(op.f("ix_lti_score_student_id"), "lti_score", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lti_score_student_id"), table_name="lti_score")
    op.drop_index(op.f("ix_lti_score_received_at"), table_name="lti_score")
    op.drop_index(op.f("ix_lti_score_line_item_id"), table_name="lti_score")
    op.drop_index("ix_lti_score_current", table_name="lti_score")
    op.drop_table("lti_score")
    op.drop_index("ix_response_marking_queue", table_name="assessment_response")
    op.drop_index(op.f("ix_assessment_response_question_id"), table_name="assessment_response")
    op.drop_index(op.f("ix_assessment_response_deleted_at"), table_name="assessment_response")
    op.drop_index(op.f("ix_assessment_response_created_by_id"), table_name="assessment_response")
    op.drop_index(op.f("ix_assessment_response_created_at"), table_name="assessment_response")
    op.drop_index(op.f("ix_assessment_response_attempt_id"), table_name="assessment_response")
    op.drop_table("assessment_response")
    op.drop_index(op.f("ix_material_view_student_id"), table_name="material_view")
    op.drop_index("ix_material_view_student", table_name="material_view")
    op.drop_index(op.f("ix_material_view_material_id"), table_name="material_view")
    op.drop_table("material_view")
    op.drop_index(op.f("ix_lti_line_item_tool_id"), table_name="lti_line_item")
    op.drop_index(op.f("ix_lti_line_item_resource_link_id"), table_name="lti_line_item")
    op.drop_index(op.f("ix_lti_line_item_resource_id"), table_name="lti_line_item")
    op.drop_index(op.f("ix_lti_line_item_deleted_at"), table_name="lti_line_item")
    op.drop_index(op.f("ix_lti_line_item_created_by_id"), table_name="lti_line_item")
    op.drop_index(op.f("ix_lti_line_item_created_at"), table_name="lti_line_item")
    op.drop_index(op.f("ix_lti_line_item_course_offering_id"), table_name="lti_line_item")
    op.drop_table("lti_line_item")
    op.drop_index("ix_submission_marking_queue", table_name="assignment_submission")
    op.drop_index(op.f("ix_assignment_submission_student_id"), table_name="assignment_submission")
    op.drop_index(op.f("ix_assignment_submission_status"), table_name="assignment_submission")
    op.drop_index(op.f("ix_assignment_submission_deleted_at"), table_name="assignment_submission")
    op.drop_index(
        op.f("ix_assignment_submission_created_by_id"), table_name="assignment_submission"
    )
    op.drop_index(op.f("ix_assignment_submission_created_at"), table_name="assignment_submission")
    op.drop_index(
        op.f("ix_assignment_submission_assignment_id"), table_name="assignment_submission"
    )
    op.drop_table("assignment_submission")
    op.drop_index(op.f("ix_assessment_item_question_id"), table_name="assessment_item")
    op.drop_index(op.f("ix_assessment_item_deleted_at"), table_name="assessment_item")
    op.drop_index(op.f("ix_assessment_item_created_by_id"), table_name="assessment_item")
    op.drop_index(op.f("ix_assessment_item_created_at"), table_name="assessment_item")
    op.drop_index(op.f("ix_assessment_item_assessment_id"), table_name="assessment_item")
    op.drop_table("assessment_item")
    op.drop_index("ix_attempt_live", table_name="assessment_attempt")
    op.drop_index(op.f("ix_assessment_attempt_total_score"), table_name="assessment_attempt")
    op.drop_index(op.f("ix_assessment_attempt_student_id"), table_name="assessment_attempt")
    op.drop_index(op.f("ix_assessment_attempt_status"), table_name="assessment_attempt")
    op.drop_index(op.f("ix_assessment_attempt_expires_at"), table_name="assessment_attempt")
    op.drop_index(op.f("ix_assessment_attempt_deleted_at"), table_name="assessment_attempt")
    op.drop_index(op.f("ix_assessment_attempt_created_by_id"), table_name="assessment_attempt")
    op.drop_index(op.f("ix_assessment_attempt_created_at"), table_name="assessment_attempt")
    op.drop_index(op.f("ix_assessment_attempt_assessment_id"), table_name="assessment_attempt")
    op.drop_table("assessment_attempt")
    op.drop_index("ix_online_assessment_window", table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_status"), table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_space_id"), table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_opens_at"), table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_kind"), table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_deleted_at"), table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_created_by_id"), table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_created_at"), table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_course_offering_id"), table_name="online_assessment")
    op.drop_index(op.f("ix_online_assessment_closes_at"), table_name="online_assessment")
    op.drop_index(
        op.f("ix_online_assessment_assessment_component_id"), table_name="online_assessment"
    )
    op.drop_table("online_assessment")
    op.drop_index(op.f("ix_material_week_number"), table_name="material")
    op.drop_index("ix_material_space_week", table_name="material")
    op.drop_index(op.f("ix_material_space_id"), table_name="material")
    op.drop_index(op.f("ix_material_kind"), table_name="material")
    op.drop_index(op.f("ix_material_is_published"), table_name="material")
    op.drop_index(op.f("ix_material_deleted_at"), table_name="material")
    op.drop_index(op.f("ix_material_created_by_id"), table_name="material")
    op.drop_index(op.f("ix_material_created_at"), table_name="material")
    op.drop_table("material")
    op.drop_index(op.f("ix_lti_resource_link_tool_id"), table_name="lti_resource_link")
    op.drop_index(op.f("ix_lti_resource_link_space_id"), table_name="lti_resource_link")
    op.drop_index(op.f("ix_lti_resource_link_deleted_at"), table_name="lti_resource_link")
    op.drop_index(op.f("ix_lti_resource_link_created_by_id"), table_name="lti_resource_link")
    op.drop_index(op.f("ix_lti_resource_link_created_at"), table_name="lti_resource_link")
    op.drop_index(op.f("ix_lti_resource_link_course_offering_id"), table_name="lti_resource_link")
    op.drop_table("lti_resource_link")
    op.drop_index(op.f("ix_content_package_status"), table_name="content_package")
    op.drop_index(op.f("ix_content_package_space_id"), table_name="content_package")
    op.drop_index(op.f("ix_content_package_question_bank_id"), table_name="content_package")
    op.drop_index(op.f("ix_content_package_format"), table_name="content_package")
    op.drop_index(op.f("ix_content_package_deleted_at"), table_name="content_package")
    op.drop_index(op.f("ix_content_package_created_by_id"), table_name="content_package")
    op.drop_index(op.f("ix_content_package_created_at"), table_name="content_package")
    op.drop_table("content_package")
    op.drop_index(op.f("ix_assignment_status"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_space_id"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_due_at"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_deleted_at"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_created_by_id"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_created_at"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_course_offering_id"), table_name="assignment")
    op.drop_table("assignment")
    op.drop_index(op.f("ix_course_space_semester_id"), table_name="course_space")
    op.drop_index(op.f("ix_course_space_is_published"), table_name="course_space")
    op.drop_index(op.f("ix_course_space_deleted_at"), table_name="course_space")
    op.drop_index(op.f("ix_course_space_created_by_id"), table_name="course_space")
    op.drop_index(op.f("ix_course_space_created_at"), table_name="course_space")
    op.drop_index(op.f("ix_course_space_course_offering_id"), table_name="course_space")
    op.drop_table("course_space")
    op.drop_index(op.f("ix_question_option_question_id"), table_name="question_option")
    op.drop_index(op.f("ix_question_option_deleted_at"), table_name="question_option")
    op.drop_index(op.f("ix_question_option_created_by_id"), table_name="question_option")
    op.drop_index(op.f("ix_question_option_created_at"), table_name="question_option")
    op.drop_table("question_option")
    op.drop_index(op.f("ix_question_topic"), table_name="question")
    op.drop_index(op.f("ix_question_kind"), table_name="question")
    op.drop_index(op.f("ix_question_is_active"), table_name="question")
    op.drop_index(op.f("ix_question_deleted_at"), table_name="question")
    op.drop_index(op.f("ix_question_created_by_id"), table_name="question")
    op.drop_index(op.f("ix_question_created_at"), table_name="question")
    op.drop_index(op.f("ix_question_cognitive_level"), table_name="question")
    op.drop_index("ix_question_bank_kind", table_name="question")
    op.drop_index(op.f("ix_question_bank_id"), table_name="question")
    op.drop_table("question")
    op.drop_index(op.f("ix_question_bank_owning_unit_id"), table_name="question_bank")
    op.drop_index(op.f("ix_question_bank_deleted_at"), table_name="question_bank")
    op.drop_index(op.f("ix_question_bank_created_by_id"), table_name="question_bank")
    op.drop_index(op.f("ix_question_bank_created_at"), table_name="question_bank")
    op.drop_index(op.f("ix_question_bank_course_id"), table_name="question_bank")
    op.drop_index(op.f("ix_question_bank_code"), table_name="question_bank")
    op.drop_table("question_bank")
    op.drop_index("ix_xapi_student_time", table_name="xapi_statement")
    op.drop_index(op.f("ix_xapi_statement_verb"), table_name="xapi_statement")
    op.drop_index(op.f("ix_xapi_statement_stored_at"), table_name="xapi_statement")
    op.drop_index(op.f("ix_xapi_statement_object_iri"), table_name="xapi_statement")
    op.drop_index(op.f("ix_xapi_statement_course_offering_id"), table_name="xapi_statement")
    op.drop_index(op.f("ix_xapi_statement_actor_student_id"), table_name="xapi_statement")
    op.drop_table("xapi_statement")
    op.drop_index(op.f("ix_lti_tool_status"), table_name="lti_tool")
    op.drop_index(op.f("ix_lti_tool_deleted_at"), table_name="lti_tool")
    op.drop_index(op.f("ix_lti_tool_created_by_id"), table_name="lti_tool")
    op.drop_index(op.f("ix_lti_tool_created_at"), table_name="lti_tool")
    op.drop_index(op.f("ix_lti_tool_client_id"), table_name="lti_tool")
    op.drop_table("lti_tool")
    op.drop_index(op.f("ix_lti_platform_key_kid"), table_name="lti_platform_key")
    op.drop_index(op.f("ix_lti_platform_key_is_active"), table_name="lti_platform_key")
    op.drop_index(op.f("ix_lti_platform_key_deleted_at"), table_name="lti_platform_key")
    op.drop_index(op.f("ix_lti_platform_key_created_by_id"), table_name="lti_platform_key")
    op.drop_index(op.f("ix_lti_platform_key_created_at"), table_name="lti_platform_key")
    op.drop_table("lti_platform_key")
    op.drop_index(op.f("ix_lti_nonce_issued_at"), table_name="lti_nonce")
    op.drop_table("lti_nonce")
    op.drop_index(op.f("ix_external_identifier_system"), table_name="external_identifier")
    op.drop_index(op.f("ix_external_identifier_resource_type"), table_name="external_identifier")
    op.drop_index(op.f("ix_external_identifier_resource_id"), table_name="external_identifier")
    op.drop_index(op.f("ix_external_identifier_external_id"), table_name="external_identifier")
    op.drop_index(op.f("ix_external_identifier_deleted_at"), table_name="external_identifier")
    op.drop_index(op.f("ix_external_identifier_created_by_id"), table_name="external_identifier")
    op.drop_index(op.f("ix_external_identifier_created_at"), table_name="external_identifier")
    op.drop_table("external_identifier")
    op.drop_index(op.f("ix_engagement_snapshot_student_id"), table_name="engagement_snapshot")
    op.drop_index(op.f("ix_engagement_snapshot_risk_band"), table_name="engagement_snapshot")
    op.drop_index(
        op.f("ix_engagement_snapshot_course_offering_id"), table_name="engagement_snapshot"
    )
    op.drop_index(op.f("ix_engagement_snapshot_captured_on"), table_name="engagement_snapshot")
    op.drop_index("ix_engagement_risk", table_name="engagement_snapshot")
    op.drop_table("engagement_snapshot")
    # ### end Alembic commands ###
